swagger: '2.0'
info:
  version: 1.0.0
  title: HTML Injection Test - Varad_PM
  description: >
    <h1>HTML Injection PoC</h1>
    <h2>Injected by Varad_PM</h2>
    <h3>This is a basic HTML payload using heading tags</h3>
paths:
  /:
    get:
      responses:
        '200':
          description: OK
