openapi: 3.0.0
info:
  title: XSS Test API
  version: 1.0.0
paths:
  /xss:
    get:
      summary: "XSS Test"
      description: |
        <img src=x onerror=alert('XSS')>
      responses:
        '200':
          description: OK
