swagger: '2.0'
info:
  version: 1.0.0
  title: Lord Ganesha Image Injected
  description: |
    ![Ganesh Ji](https://raw.githubusercontent.com/menevarad007/swagger-xss/main/savage.jpg)

    Above is a Ganesha image via direct Markdown.
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
