swagger: '2.0'
info:
  version: 1.0.0
  title: Markdown Image Injection
  description: |
    ![PoC](https://i.imgur.com/BrXWvdL.jpg)

    This image was injected using Markdown.
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
