swagger: '2.0'
info:
  version: 1.0.0
  title: Lord Ganesha Image Injected
  description: |
    ![Ganesh Ji](https://upload.wikimedia.org/wikipedia/commons/6/64/Ganesha.svg)

    This image is injected via Markdown and renders properly inside Swagger UI.
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
