swagger: '2.0'
info:
  version: 1.0.0
  title: HTML Injection by Varad_PM
  description: |
    <h1>HTML Injection PoC by Varad_PM</h1>

    ![Ganesh Ji](https://raw.githubusercontent.com/menevarad007/swagger-xss/main/savage.jpg)

    This image was injected into Swagger using Markdown syntax.
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
