swagger: '2.0'
info:
  version: 1.0.0
  title: HTML Injection SVG
  description: >
    <svg xmlns="http://www.w3.org/2000/svg"><script>alert(document.domain)</script></svg>
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
