swagger: '2.0'
info:
  version: 1.0.0
  title: HTML Injection IMG injected
  description: >
    <img src=x o&#110;error=&#97;lert(document.domain)>
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
